#!/bin/sh

# path:       ~/.config/sxiv/exec/image-info
# user:       klassiker [mrdotx]
# github:     https://github.com/mrdotx/dotfiles
# date:       2020-01-13T12:41:11+0100

# field separator
s="  "

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"

echo "${filesize}${s}${geometry}${s}${filename}"
