#!/bin/sh

# path:   /home/klassiker/.config/sxiv/exec/image-info
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2021-05-28T10:08:16+0200

# $1: path to image file
# $2: image width
# $3: image height

printf "%s | %dx%d | %s | %s" \
    "$(du -Hh "$1" | cut -f 1)" \
    "$2" \
    "$3" \
    "$(basename "$1")" \
    "$(date '+%d.%m.%Y %H:%M' -r "$1")"
