#!/bin/sh

# path:       ~/.config/sxiv/exec/key-handler
# user:       klassiker [mrdotx]
# github:     https://github.com/mrdotx/dotfiles
# date:       2019-12-02 22:09:45

# rotate function
rotate() {
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort -u | while read -r file; do
        case "$(file -b -i "$file")" in
        image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
        *)           mogrify  -rotate "$degree" "$file" ;;
        esac
    done
}

# flip function
flip() {
    direction="$1"
    tr '\n' '\0' | xargs -0 realpath | sort -u | while read -r file; do
        case "$(file -b -i "$file")" in
        image/jpeg*) jpegtran -flip "$direction" -copy all -outfile "$file" "$file" ;;
        *)           if [ "$direction" = "horizontal" ]; then
                        mogrify -flop "$file"
                     elif [ "$direction" = "vertical" ]; then
                        mogrify -flip "$file"
                     fi ;;
        esac
    done
}


# trash function
trash() {
    tr '\n' '\0' | xargs -0 realpath | sort -u | while read -r file; do
        case "$(file -b -i "$file")" in
        *) gio trash "$file" && notify-send "sxiv" "$file moved to trash" --icon=messagebox_warning ;;
        esac
    done
}

# keybindings
case "$1" in
    "C-e")          while read -r file; do $TERMINAL -T "$file" -e sh -c "exiftool '$file' | less" & done ;;
    "C-w")          while read -r file; do nitrogen --save --set-zoom-fill "$file" & done && notify-send "sxiv" "wallpaper changed" --icon=messagebox_info ;;
    "C-g")          tr '\n' '\0' | xargs -0 gimp & ;;
    "C-n")          tr '\n' '\0' | xargs -0 nomacs & ;;
    "C-comma")      rotate 270 ;;
    "C-period")     rotate  90 ;;
    "C-slash")      rotate 180 ;;
    "C-semicolon")  flip 'horizontal' ;;
    "C-apostrophe") flip 'vertical' ;;
    "C-d")          trash ;;
esac
