#!/bin/sh

# path:   /home/klassiker/.local/share/repos/dotfiles/.config/sxiv/exec/key-handler
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2021-05-28T11:57:21+0200

# rotate function
rotate() {
    degree="$1"
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                image/jpeg*)
                    jpegtran -rotate "$degree" -copy all -outfile "$file" "$file"
                    ;;
                *)
                    mogrify  -rotate "$degree" "$file"
                    ;;
            esac
        done
}

# flip function
flip() {
    direction="$1"
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                image/jpeg*)
                    jpegtran -flip "$direction" -copy all -outfile "$file" "$file"
                    ;;
                *)
                    if [ "$direction" = "horizontal" ]; then
                        mogrify -flop "$file"
                    elif [ "$direction" = "vertical" ]; then
                        mogrify -flip "$file"
                    fi
                    ;;
            esac
        done
}

# trash function
trash() {
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                *)
                    trash-put "$file" \
                        && notify-send \
                            "sxiv" \
                            "$file moved to trash" \
                            --icon=messagebox_warning
                    ;;
        esac
    done
}

# wallaper function
wallpaper() {
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                *)
                    wallpaper.sh "$file" \
                        && notify-send \
                            "sxiv" \
                            "$file set as wallpaper"
                    ;;
        esac
    done
}

# keybindings
case "$1" in
    "C-e")
        while read -r file; do $TERMINAL -T "$file" -e \
            sh -c "exiftool '$file' | less" \
            & done
        ;;
    "C-w")
        wallpaper
        ;;
    "C-g")
        tr '\n' '\0' \
            | xargs -0 gimp &
        ;;
    "C-comma")
        rotate 270
        ;;
    "C-period")
        rotate 90
        ;;
    "C-slash")
        rotate 180
        ;;
    "C-semicolon")
        flip 'horizontal'
        ;;
    "C-apostrophe")
        flip 'vertical'
        ;;
    "C-d")
        trash
        ;;
esac
