# path:   /home/klassiker/.local/share/repos/dotfiles/.config/polybar/config.d/i3.ini
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2022-05-03T13:50:43+0200

[module/i3]
    type = internal/i3
    pin-workspaces = ${env:I3PIN:false}
    index-sort = true
    wrapping-scroll = false
    ws-icon-1 = 1;ﭱ 1
    ws-icon-2 = 2;ﲵ 2
    ws-icon-3 = 3; 3
    ws-icon-4 = 4; 4
    ws-icon-5 = 5; 5
    ws-icon-6 = 6; 6
    ws-icon-7 = 7;ﴝ 7
    ws-icon-8 = 8; 8
    ws-icon-9 = 9;兀 9
    ws-icon-0 = 10;襁 0
    ws-icon-default = 
    format = <label-state>
    label-focused = %icon%
    label-focused-font = 4
    label-focused-background = ${colors.primary}
    label-focused-overline = ${colors.foreground}
    label-focused-padding = 1
    label-unfocused = %icon%
    label-unfocused-font = 4
    label-unfocused-background = ${colors.background}
    label-unfocused-overline = ${colors.secondary}
    label-unfocused-padding = 1
    label-visible = %icon%
    label-visible-font = 4
    label-visible-background = ${colors.secondary}
    label-visible-overline = ${colors.foreground}
    label-visible-padding = 1
    label-urgent = %icon%
    label-urgent-font = 4
    label-urgent-foreground = ${colors.black}
    label-urgent-background = ${colors.red}
    label-urgent-overline = ${colors.red}
    label-urgent-padding = 1
