; path:   /home/klassiker/Projects/repos/dotfiles/.config/polybar/config.d/ipc_timer.ini
; author: klassiker [mrdotx]
; url:    https://github.com/mrdotx/dotfiles
; date:   2026-07-17T02:32:32+0200

[module/ipc_timer]
    type = custom/script
    label =

[module/rss_timer]
    inherit = module/ipc_timer
    exec = polybar_freshrss.sh --update
    interval = 1200

[module/trash_timer]
    inherit = module/ipc_timer
    exec = polybar_trash-cli.sh --update
    interval = 300

[module/packages_timer]
    inherit = module/ipc_timer
    exec = polybar_pacman.sh --update
    interval = 10800

[module/weather_timer]
    inherit = module/ipc_timer
    exec = polybar_openweather.sh --update
    interval = 900
