# path:   /home/klassiker/.local/share/repos/dotfiles/.config/polybar/config.d/memory.ini
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2022-04-19T20:09:47+0200

[module/ram]
    type = internal/memory
    interval = 2.0
    warn-percentage = 80
    format = <bar-used> <label>
    format-prefix = " "
    label = %gb_used%
    bar-used-width = 20
    bar-used-fill = ı
    bar-used-indicator = ı
    bar-used-empty = ı
    bar-used-empty-foreground = ${colors.foreground1}
    bar-used-foreground-0 = ${colors.main}
    bar-used-foreground-1 = ${colors.main}
    bar-used-foreground-2 = ${colors.main}
    bar-used-foreground-3 = ${colors.yellow}
    bar-used-foreground-4 = ${colors.red}

[module/swap]
    inherit = module/ram
    warn-percentage = 50
    format = <bar-swap-used> <label>
    format-prefix = " "
    label = %gb_swap_used%
    bar-swap-used-width = 20
    bar-swap-used-fill = ı
    bar-swap-used-indicator = ı
    bar-swap-used-empty = ı
    bar-swap-used-empty-foreground = ${colors.foreground1}
    bar-swap-used-foreground-0 = ${colors.main}
    bar-swap-used-foreground-1 = ${colors.main}
    bar-swap-used-foreground-2 = ${colors.main}
    bar-swap-used-foreground-3 = ${colors.yellow}
    bar-swap-used-foreground-4 = ${colors.red}
