; path:   /home/klassiker/Projects/repos/dotfiles/.config/polybar/config.d/script.ini
; author: klassiker [mrdotx]
; url:    https://github.com/mrdotx/dotfiles
; date:   2026-07-17T02:32:44+0200

[module/script]
    type = custom/script
    interval = 5.0
    interval-fail = 60.0

[module/fritzbox]
    inherit = module/script
    format-prefix = %{T2}󱂇 %{T-}
    exec = fritzbox.sh --bar
