; path:   /home/klassiker/Projects/repos/dotfiles/.config/polybar/config.d/tray.ini
; author: klassiker [mrdotx]
; url:    https://github.com/mrdotx/dotfiles
; date:   2026-07-17T02:32:50+0200

[module/tray]
    type = internal/tray
