; path:   /home/klassiker/.local/share/repos/dotfiles/.config/polybar/config.d/xkeyboard.ini
; author: klassiker [mrdotx]
; url:    https://github.com/mrdotx/dotfiles
; date:   2026-07-05T05:13:10+0200

[module/xkeyboard]
    type = internal/xkeyboard
    label-layout = %icon%%layout%
    layout-icon-default = %{T2}󰌏 %{T-}
    layout-icon-0 = us;%{T2}󰌌 %{T-}
    indicator-icon-0 = caps lock;;󰬈
    indicator-icon-1 = num lock;;󰎤
    indicator-icon-2 = scroll lock;;󰛀
    label-indicator-on = "%{T2}%icon%%{T-} "
    label-indicator-on-foreground = ${colors.primary}
