#!/bin/sh

# path:   /home/klassiker/.local/share/repos/dotfiles/.config/X11/xinit/xinitrc
# author: klassiker [mrdotx]
# url:    https://github.com/mrdotx/dotfiles
# date:   2025-08-05T05:42:20+0200

# load defaults and keymaps
[ -f "/etc/X11/xinit/.Xresources" ] \
    && xrdb -merge "/etc/X11/xinit/.Xresources"
[ -f "/etc/X11/xinit/.Xmodmap" ] \
    && xmodmap "/etc/X11/xinit/.Xmodmap"
[ -f "$HOME/.config/X11/Xresources" ] \
    && xrdb -merge "$HOME/.config/X11/Xresources"
[ -f "$HOME/.config/X11/Xmodmap" ] \
    && xmodmap "$HOME/.config/X11/Xmodmap"

# start scripts
[ -d "/etc/X11/xinit/xinitrc.d" ] \
    && for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] \
            && . "$f"
    done \
    && unset f
[ -d "$HOME/.config/X11/xinit/xinitrc.d" ] \
    && for f in "$HOME"/.config/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] \
            && . "$f"
    done \
    && unset f

# start session
session="${1:-i3}"
[ "$TERM" = linux ] \
    && case "$session" in
        i3-debug)
            exec i3 --shmlog-size=26214400
            ;;
        kodi)
            exec kodi-standalone
            ;;
        xfce)
            exec startxfce4
            ;;
        *)
            exec "$session"
            ;;
    esac
