#!/bin/sh

# path:   /home/klassiker/Projects/repos/dotfiles/.config/nsxiv/exec/image-info
# author: klassiker [mrdotx]
# url:    https://github.com/mrdotx/dotfiles
# date:   2026-07-17T02:28:12+0200

# $1: path to image file (as provided by the user)
# $2: image width
# $3: image height
# $4: fully resolved path to the image file

printf "» %s │ %s │ %s | %dx%d «" \
    "$(basename "$1")" \
    "$(date '+%d.%m.%Y %H:%M' -r "$1")" \
    "$(du -Hh "$1" | cut -f1)" \
    "$2" \
    "$3"
