#!/bin/sh

# path:   /home/klassiker/.local/share/repos/dotfiles/.config/nsxiv/exec/image-info
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2024-11-30T07:07:49+0100

# $1: path to image file (as provided by the user)
# $2: image width
# $3: image height
# $4: fully resolved path to the image file

printf "» %dx%d │ %s │ %s │ %s «" \
    "$2" \
    "$3" \
    "$(du -Hh "$1" | cut -f1)" \
    "$(date '+%d.%m.%Y %H:%M' -r "$1")" \
    "$(basename "$1")"
