#!/bin/sh

# path:   /home/klassiker/.local/share/repos/dotfiles/.config/xorg/Xinitrc
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dotfiles
# date:   2021-07-25T20:29:52+0200

# set cpu policy
cpu_policy.sh --performance

# load xorg defaults and keymaps
[ -f "/etc/X11/xinit/.Xresources" ] \
    && xrdb -merge "/etc/X11/xinit/.Xresources"
[ -f "/etc/X11/xinit/.Xmodmap" ] \
    && xmodmap "/etc/X11/xinit/.Xmodmap"
[ -f "$HOME/.config/xorg/Xresources" ] \
    && xrdb -merge "$HOME/.config/xorg/Xresources"
[ -f "$HOME/.config/xorg/Xmodmap" ] \
    && xmodmap "$HOME/.config/xorg/Xmodmap"

# start xorg scripts
[ -d "/etc/X11/xinit/xinitrc.d" ] \
    && for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] \
            && . "$f"
    done \
    && unset f

# set gnupg ssh agent support
unset SSH_AGENT_PID
[ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ] \
    && SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)" \
    && export SSH_AUTH_SOCK

# set peripheral devices
setxkbmap \
    -model "pc105" \
    -layout "us,de" \
    -option "grp:caps_switch" &
xset r rate 200 50 &
xinput \
    --set-prop "Synaptics TM3242-001" "libinput Tapping Enabled" 0 &
xinput \
    --set-prop "Synaptics TM3242-001" "libinput Natural Scrolling Enabled" 1 &

# set desktop
screenlayout.sh &
wallpaper.sh &

# start session
session="${1:-i3}"
[ "$TERM" = linux ] \
    && case "$session" in
        i3)
            exec i3
            ;;
        i3-debug)
            exec i3 --shmlog-size=26214400
            ;;
        kodi)
            exec kodi-standalone
            ;;
        *)
            exec "$1"
            ;;
    esac
